"""Production Feature Catalog for FeatureHub.
Contains 125 concrete features across customer, merchant, transaction, and device entities.
Strictly adheres to all 8 mandatory attributes:
  - name
  - type
  - description
  - entity
  - source
  - timestamp
  - owner
  - version
"""

from typing import List
from featurehub.registry.metadata import FeatureDefinition, FeatureType

CATALOG_TIMESTAMP = "2026-09-24T12:00:00+00:00"

def get_all_features() -> List[FeatureDefinition]:
    """Returns the full catalog of 125 production features."""
    features: List[FeatureDefinition] = []

    # =========================================================================
    # 1. CUSTOMER ENTITY FEATURES (35 Features)
    # =========================================================================
    customer_features = [
        # Customer Velocity
        FeatureDefinition(
            name="customer_tx_count_1h",
            type=FeatureType.INT.value,
            description="Total count of transactions initiated by the customer in the trailing 1 hour window.",
            entity="customer",
            source="postgresql.analytics.fact_transactions_hourly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.2.0",
            tags=["velocity", "short-term", "fraud-signal"],
            freshness_sla_seconds=300,
            default_value=0,
        ),
        FeatureDefinition(
            name="customer_tx_count_24h",
            type=FeatureType.INT.value,
            description="Total count of transactions initiated by the customer in the trailing 24 hours.",
            entity="customer",
            source="postgresql.analytics.fact_transactions_daily",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.2.0",
            tags=["velocity", "daily", "baseline"],
            freshness_sla_seconds=1800,
            default_value=0,
        ),
        FeatureDefinition(
            name="customer_tx_count_7d",
            type=FeatureType.INT.value,
            description="Total count of settled transactions over the trailing 7 calendar days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_weekly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["velocity", "weekly"],
            freshness_sla_seconds=7200,
            default_value=0,
        ),
        FeatureDefinition(
            name="customer_tx_count_30d",
            type=FeatureType.INT.value,
            description="Total count of settled transactions over the trailing 30 calendar days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_monthly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["velocity", "monthly"],
            freshness_sla_seconds=14400,
            default_value=0,
        ),
        FeatureDefinition(
            name="customer_spend_amount_1h",
            type=FeatureType.FLOAT.value,
            description="Total dollar amount spent by the customer within the last 1 hour.",
            entity="customer",
            source="postgresql.analytics.fact_transactions_hourly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.2.0",
            tags=["spend", "burst-detection"],
            freshness_sla_seconds=300,
            default_value=0.0,
        ),
        FeatureDefinition(
            name="customer_spend_amount_24h",
            type=FeatureType.FLOAT.value,
            description="Total gross transaction volume authorized in the last 24 hours.",
            entity="customer",
            source="postgresql.analytics.fact_transactions_daily",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.2.0",
            tags=["spend", "daily"],
            freshness_sla_seconds=1800,
            default_value=0.0,
        ),
        FeatureDefinition(
            name="customer_spend_amount_7d",
            type=FeatureType.FLOAT.value,
            description="Cumulative transaction spend over the last 7 calendar days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_weekly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["spend", "weekly"],
            freshness_sla_seconds=7200,
            default_value=0.0,
        ),
        FeatureDefinition(
            name="customer_spend_amount_30d",
            type=FeatureType.FLOAT.value,
            description="Cumulative transaction spend over the last 30 calendar days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_monthly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["spend", "monthly"],
            freshness_sla_seconds=14400,
            default_value=0.0,
        ),
        FeatureDefinition(
            name="customer_avg_spend_amount_30d",
            type=FeatureType.FLOAT.value,
            description="Average transaction amount calculated over the last 30 days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_monthly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["spend", "baseline"],
            freshness_sla_seconds=14400,
            default_value=50.0,
        ),
        FeatureDefinition(
            name="customer_stddev_spend_amount_30d",
            type=FeatureType.FLOAT.value,
            description="Standard deviation of transaction amounts in the last 30 days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_monthly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["statistics", "variance"],
            freshness_sla_seconds=14400,
            default_value=25.0,
        ),
        FeatureDefinition(
            name="customer_max_spend_amount_30d",
            type=FeatureType.FLOAT.value,
            description="Highest single transaction amount authorized in the last 30 days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_monthly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["spend", "extremes"],
            freshness_sla_seconds=14400,
            default_value=200.0,
        ),
        FeatureDefinition(
            name="customer_distinct_merchants_24h",
            type=FeatureType.INT.value,
            description="Count of unique merchants transacted with in the last 24 hours.",
            entity="customer",
            source="postgresql.analytics.fact_transactions_daily",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["diversity", "velocity"],
            freshness_sla_seconds=1800,
            default_value=1,
        ),
        FeatureDefinition(
            name="customer_distinct_merchants_7d",
            type=FeatureType.INT.value,
            description="Count of unique merchants transacted with in the last 7 days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_weekly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["diversity", "weekly"],
            freshness_sla_seconds=7200,
            default_value=3,
        ),
        FeatureDefinition(
            name="customer_distinct_categories_7d",
            type=FeatureType.INT.value,
            description="Number of distinct MCC (Merchant Category Codes) visited in 7 days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_weekly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["mcc", "behavior"],
            freshness_sla_seconds=7200,
            default_value=2,
        ),
        FeatureDefinition(
            name="customer_distinct_countries_7d",
            type=FeatureType.INT.value,
            description="Count of distinct ISO country codes where transactions originated in 7 days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_weekly",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["geo", "cross-border"],
            freshness_sla_seconds=7200,
            default_value=1,
        ),
        FeatureDefinition(
            name="customer_distinct_cities_24h",
            type=FeatureType.INT.value,
            description="Count of distinct cities logged in transaction coordinates over 24 hours.",
            entity="customer",
            source="postgresql.analytics.fact_transactions_daily",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["geo", "velocity"],
            freshness_sla_seconds=1800,
            default_value=1,
        ),
        # Customer Behavioral & Risk
        FeatureDefinition(
            name="customer_failed_tx_count_24h",
            type=FeatureType.INT.value,
            description="Count of failed or declined transaction authorization attempts in 24 hours.",
            entity="customer",
            source="postgresql.analytics.fact_declines_daily",
            timestamp=CATALOG_TIMESTAMP,
            owner="risk-eng@lakeflow.io",
            version="1.3.0",
            tags=["declines", "brute-force", "high-signal"],
            freshness_sla_seconds=900,
            default_value=0,
        ),
        FeatureDefinition(
            name="customer_failed_pin_count_24h",
            type=FeatureType.INT.value,
            description="Number of incorrect ATM/POS PIN attempts within the last 24 hours.",
            entity="customer",
            source="postgresql.analytics.fact_pin_events_daily",
            timestamp=CATALOG_TIMESTAMP,
            owner="risk-eng@lakeflow.io",
            version="1.1.0",
            tags=["pin", "physical-security"],
            freshness_sla_seconds=900,
            default_value=0,
        ),
        FeatureDefinition(
            name="customer_refund_count_30d",
            type=FeatureType.INT.value,
            description="Number of processed refunds or reverse settlements credited in 30 days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_monthly",
            timestamp=CATALOG_TIMESTAMP,
            owner="risk-eng@lakeflow.io",
            version="1.0.0",
            tags=["refunds"],
            freshness_sla_seconds=14400,
            default_value=0,
        ),
        FeatureDefinition(
            name="customer_refund_ratio_30d",
            type=FeatureType.FLOAT.value,
            description="Ratio of refunded transaction volume to total authorization volume in 30 days.",
            entity="customer",
            source="postgresql.analytics.customer_aggregates_monthly",
            timestamp=CATALOG_TIMESTAMP,
            owner="risk-eng@lakeflow.io",
            version="1.0.0",
            tags=["refunds", "ratio"],
            freshness_sla_seconds=14400,
            default_value=0.0,
        ),
        FeatureDefinition(
            name="customer_chargeback_count_lifetime",
            type=FeatureType.INT.value,
            description="Total lifetime disputes and chargebacks filed against customer account.",
            entity="customer",
            source="postgresql.public.customer_dispute_history",
            timestamp=CATALOG_TIMESTAMP,
            owner="compliance@lakeflow.io",
            version="2.0.0",
            tags=["chargeback", "lifetime", "high-risk"],
            freshness_sla_seconds=86400,
            default_value=0,
        ),
        FeatureDefinition(
            name="customer_chargeback_rate_lifetime",
            type=FeatureType.FLOAT.value,
            description="Lifetime chargeback count divided by lifetime settled transaction count.",
            entity="customer",
            source="postgresql.public.customer_dispute_history",
            timestamp=CATALOG_TIMESTAMP,
            owner="compliance@lakeflow.io",
            version="2.0.0",
            tags=["chargeback", "rate"],
            freshness_sla_seconds=86400,
            default_value=0.0,
        ),
        FeatureDefinition(
            name="customer_days_since_first_tx",
            type=FeatureType.FLOAT.value,
            description="Tenure of the customer account measured in days since first authorized payment.",
            entity="customer",
            source="postgresql.public.customer_profiles",
            timestamp=CATALOG_TIMESTAMP,
            owner="core-data@lakeflow.io",
            version="1.0.0",
            tags=["tenure", "trust"],
            freshness_sla_seconds=86400,
            default_value=120.0,
        ),
        FeatureDefinition(
            name="customer_days_since_last_tx",
            type=FeatureType.FLOAT.value,
            description="Time elapsed in decimal days since the customer previous transaction.",
            entity="customer",
            source="postgresql.analytics.customer_recency",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["recency"],
            freshness_sla_seconds=1800,
            default_value=1.5,
        ),
        FeatureDefinition(
            name="customer_days_since_password_reset",
            type=FeatureType.FLOAT.value,
            description="Days elapsed since the last digital banking password update or credential reset.",
            entity="customer",
            source="postgresql.iam.user_credentials_audit",
            timestamp=CATALOG_TIMESTAMP,
            owner="security@lakeflow.io",
            version="1.1.0",
            tags=["account-takeover", "security"],
            freshness_sla_seconds=3600,
            default_value=45.0,
        ),
        FeatureDefinition(
            name="customer_days_since_phone_change",
            type=FeatureType.FLOAT.value,
            description="Days elapsed since primary 2FA mobile phone number modification (SIM swap signal).",
            entity="customer",
            source="postgresql.iam.user_credentials_audit",
            timestamp=CATALOG_TIMESTAMP,
            owner="security@lakeflow.io",
            version="1.2.0",
            tags=["sim-swap", "ato", "high-risk"],
            freshness_sla_seconds=3600,
            default_value=90.0,
        ),
        FeatureDefinition(
            name="customer_days_since_email_change",
            type=FeatureType.FLOAT.value,
            description="Days elapsed since primary registered email address change.",
            entity="customer",
            source="postgresql.iam.user_credentials_audit",
            timestamp=CATALOG_TIMESTAMP,
            owner="security@lakeflow.io",
            version="1.1.0",
            tags=["ato", "security"],
            freshness_sla_seconds=3600,
            default_value=120.0,
        ),
        FeatureDefinition(
            name="customer_kyc_verification_level",
            type=FeatureType.INT.value,
            description="KYC verification status level (1: Email only, 2: ID verified, 3: Biometric/Proof of Address).",
            entity="customer",
            source="postgresql.compliance.kyc_records",
            timestamp=CATALOG_TIMESTAMP,
            owner="compliance@lakeflow.io",
            version="1.0.0",
            tags=["kyc", "identity"],
            freshness_sla_seconds=86400,
            default_value=2,
        ),
        FeatureDefinition(
            name="customer_credit_score",
            type=FeatureType.INT.value,
            description="FICO / bureau credit rating score (300 to 850 scale).",
            entity="customer",
            source="postgresql.bureau.credit_scores",
            timestamp=CATALOG_TIMESTAMP,
            owner="credit-risk@lakeflow.io",
            version="1.0.0",
            tags=["credit", "risk"],
            freshness_sla_seconds=86400,
            default_value=720,
        ),
        FeatureDefinition(
            name="customer_current_balance",
            type=FeatureType.FLOAT.value,
            description="Real-time available checking balance in USD.",
            entity="customer",
            source="postgresql.ledger.account_balances",
            timestamp=CATALOG_TIMESTAMP,
            owner="core-banking@lakeflow.io",
            version="1.4.0",
            tags=["balance", "financial"],
            freshness_sla_seconds=60,
            default_value=2500.0,
        ),
        FeatureDefinition(
            name="customer_credit_utilization_ratio",
            type=FeatureType.FLOAT.value,
            description="Percentage of revolving credit line currently utilized (0.00 to 1.00).",
            entity="customer",
            source="postgresql.ledger.credit_lines",
            timestamp=CATALOG_TIMESTAMP,
            owner="credit-risk@lakeflow.io",
            version="1.0.0",
            tags=["credit", "utilization"],
            freshness_sla_seconds=86400,
            default_value=0.25,
        ),
        FeatureDefinition(
            name="customer_overdraft_count_90d",
            type=FeatureType.INT.value,
            description="Count of Non-Sufficient Funds (NSF) / overdraft episodes in trailing 90 days.",
            entity="customer",
            source="postgresql.ledger.nsf_events",
            timestamp=CATALOG_TIMESTAMP,
            owner="credit-risk@lakeflow.io",
            version="1.0.0",
            tags=["overdraft", "delinquency"],
            freshness_sla_seconds=86400,
            default_value=0,
        ),
        FeatureDefinition(
            name="customer_is_vip",
            type=FeatureType.BOOL.value,
            description="Flag identifying private banking and high-wealth concierge tier accounts.",
            entity="customer",
            source="postgresql.public.customer_segments",
            timestamp=CATALOG_TIMESTAMP,
            owner="growth-team@lakeflow.io",
            version="1.0.0",
            tags=["segment", "vip"],
            freshness_sla_seconds=86400,
            default_value=False,
        ),
        FeatureDefinition(
            name="customer_is_politically_exposed",
            type=FeatureType.BOOL.value,
            description="OFAC / PEP sanctions compliance flag indicating politically exposed person.",
            entity="customer",
            source="postgresql.compliance.sanctions_watch",
            timestamp=CATALOG_TIMESTAMP,
            owner="compliance@lakeflow.io",
            version="1.0.0",
            tags=["compliance", "pep"],
            freshness_sla_seconds=86400,
            default_value=False,
        ),
        FeatureDefinition(
            name="customer_risk_tier",
            type=FeatureType.INT.value,
            description="Composite customer risk rating category (1: Minimal, 2: Standard, 3: Monitored, 4: High).",
            entity="customer",
            source="postgresql.analytics.customer_risk_profile",
            timestamp=CATALOG_TIMESTAMP,
            owner="risk-eng@lakeflow.io",
            version="2.1.0",
            tags=["risk-tier", "composite"],
            freshness_sla_seconds=3600,
            default_value=2,
        ),
    ]
    features.extend(customer_features)

    # =========================================================================
    # 2. MERCHANT ENTITY FEATURES (30 Features)
    # =========================================================================
    merchant_features = [
        FeatureDefinition(
            name="merchant_tx_count_1h",
            type=FeatureType.INT.value,
            description="Gross inbound transactions received by merchant across all terminals in 1 hour.",
            entity="merchant",
            source="postgresql.analytics.merchant_hourly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.1.0",
            tags=["velocity", "inflow"],
            freshness_sla_seconds=300,
            default_value=15,
        ),
        FeatureDefinition(
            name="merchant_tx_count_24h",
            type=FeatureType.INT.value,
            description="Total count of transactions cleared by merchant in the last 24 hours.",
            entity="merchant",
            source="postgresql.analytics.merchant_daily_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.1.0",
            tags=["volume", "daily"],
            freshness_sla_seconds=1800,
            default_value=320,
        ),
        FeatureDefinition(
            name="merchant_tx_count_7d",
            type=FeatureType.INT.value,
            description="Cumulative weekly volume of transactions cleared by merchant in trailing 7 days.",
            entity="merchant",
            source="postgresql.analytics.merchant_weekly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.0.0",
            tags=["volume", "weekly"],
            freshness_sla_seconds=7200,
            default_value=2200,
        ),
        FeatureDefinition(
            name="merchant_tx_volume_24h",
            type=FeatureType.FLOAT.value,
            description="Dollar sum volume cleared by merchant in the trailing 24 hours.",
            entity="merchant",
            source="postgresql.analytics.merchant_daily_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.1.0",
            tags=["volume", "dollar-cleared"],
            freshness_sla_seconds=1800,
            default_value=18500.0,
        ),
        FeatureDefinition(
            name="merchant_tx_volume_7d",
            type=FeatureType.FLOAT.value,
            description="Dollar sum volume cleared by merchant in trailing 7 days.",
            entity="merchant",
            source="postgresql.analytics.merchant_weekly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.0.0",
            tags=["volume", "weekly-dollar"],
            freshness_sla_seconds=7200,
            default_value=125000.0,
        ),
        FeatureDefinition(
            name="merchant_avg_tx_amount_30d",
            type=FeatureType.FLOAT.value,
            description="30-day mean transaction ticket size at merchant.",
            entity="merchant",
            source="postgresql.analytics.merchant_monthly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.0.0",
            tags=["ticket-size", "baseline"],
            freshness_sla_seconds=14400,
            default_value=55.0,
        ),
        FeatureDefinition(
            name="merchant_stddev_tx_amount_30d",
            type=FeatureType.FLOAT.value,
            description="Standard deviation of ticket size at merchant over 30 days.",
            entity="merchant",
            source="postgresql.analytics.merchant_monthly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.0.0",
            tags=["ticket-size", "variance"],
            freshness_sla_seconds=14400,
            default_value=32.0,
        ),
        FeatureDefinition(
            name="merchant_max_single_tx_amount_30d",
            type=FeatureType.FLOAT.value,
            description="Highest single transaction authorization cleared by merchant in 30 days.",
            entity="merchant",
            source="postgresql.analytics.merchant_monthly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.0.0",
            tags=["ticket-size", "spike"],
            freshness_sla_seconds=14400,
            default_value=850.0,
        ),
        FeatureDefinition(
            name="merchant_distinct_cards_24h",
            type=FeatureType.INT.value,
            description="Count of distinct credit/debit PAN hashes charged at merchant in 24 hours.",
            entity="merchant",
            source="postgresql.analytics.merchant_daily_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["diversity", "card-testing"],
            freshness_sla_seconds=1800,
            default_value=280,
        ),
        FeatureDefinition(
            name="merchant_distinct_customers_7d",
            type=FeatureType.INT.value,
            description="Count of distinct customer bank IDs transacting at merchant in 7 days.",
            entity="merchant",
            source="postgresql.analytics.merchant_weekly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["diversity", "shopper-base"],
            freshness_sla_seconds=7200,
            default_value=1750,
        ),
        FeatureDefinition(
            name="merchant_fraud_reports_count_30d",
            type=FeatureType.INT.value,
            description="Confirmed fraud incident reports filed by issuing banks against merchant in 30d.",
            entity="merchant",
            source="postgresql.risk.tc40_fraud_reports",
            timestamp=CATALOG_TIMESTAMP,
            owner="compliance@lakeflow.io",
            version="2.0.0",
            tags=["fraud", "tc40", "critical"],
            freshness_sla_seconds=3600,
            default_value=1,
        ),
        FeatureDefinition(
            name="merchant_fraud_rate_30d",
            type=FeatureType.FLOAT.value,
            description="Ratio of confirmed fraudulent transactions to total volume in 30 days.",
            entity="merchant",
            source="postgresql.risk.tc40_fraud_reports",
            timestamp=CATALOG_TIMESTAMP,
            owner="compliance@lakeflow.io",
            version="2.0.0",
            tags=["fraud-rate", "key-metric"],
            freshness_sla_seconds=3600,
            default_value=0.002,
        ),
        FeatureDefinition(
            name="merchant_chargeback_count_30d",
            type=FeatureType.INT.value,
            description="Total chargeback notices received from Visa/Mastercard networks in 30 days.",
            entity="merchant",
            source="postgresql.disputes.chargeback_queue",
            timestamp=CATALOG_TIMESTAMP,
            owner="disputes-ops@lakeflow.io",
            version="1.2.0",
            tags=["chargeback", "dispute"],
            freshness_sla_seconds=3600,
            default_value=2,
        ),
        FeatureDefinition(
            name="merchant_chargeback_ratio_30d",
            type=FeatureType.FLOAT.value,
            description="Card scheme chargeback basis ratio (monitoring breach if > 0.009).",
            entity="merchant",
            source="postgresql.disputes.chargeback_queue",
            timestamp=CATALOG_TIMESTAMP,
            owner="disputes-ops@lakeflow.io",
            version="1.2.0",
            tags=["chargeback", "card-scheme"],
            freshness_sla_seconds=3600,
            default_value=0.003,
        ),
        FeatureDefinition(
            name="merchant_refund_count_30d",
            type=FeatureType.INT.value,
            description="Total customer refunds executed by merchant in 30 days.",
            entity="merchant",
            source="postgresql.analytics.merchant_monthly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.0.0",
            tags=["refunds"],
            freshness_sla_seconds=14400,
            default_value=18,
        ),
        FeatureDefinition(
            name="merchant_refund_rate_30d",
            type=FeatureType.FLOAT.value,
            description="Ratio of refund authorizations to sales authorizations in 30 days.",
            entity="merchant",
            source="postgresql.analytics.merchant_monthly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.0.0",
            tags=["refund-rate"],
            freshness_sla_seconds=14400,
            default_value=0.025,
        ),
        FeatureDefinition(
            name="merchant_dispute_win_rate_90d",
            type=FeatureType.FLOAT.value,
            description="Percentage of representment cases won by merchant in last 90 days (0.0 to 1.0).",
            entity="merchant",
            source="postgresql.disputes.representment_results",
            timestamp=CATALOG_TIMESTAMP,
            owner="disputes-ops@lakeflow.io",
            version="1.0.0",
            tags=["dispute", "representment"],
            freshness_sla_seconds=86400,
            default_value=0.68,
        ),
        FeatureDefinition(
            name="merchant_risk_score",
            type=FeatureType.FLOAT.value,
            description="Normalized internal merchant underwriting risk score (0.00 to 1.00).",
            entity="merchant",
            source="postgresql.analytics.merchant_underwriting",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="2.0.0",
            tags=["risk-score", "ml-feature"],
            freshness_sla_seconds=3600,
            default_value=0.15,
        ),
        FeatureDefinition(
            name="merchant_category_risk_index",
            type=FeatureType.FLOAT.value,
            description="Industry baseline risk factor for merchant MCC code (e.g., electronics=0.6, groceries=0.1).",
            entity="merchant",
            source="postgresql.analytics.mcc_benchmarks",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["mcc", "industry-risk"],
            freshness_sla_seconds=86400,
            default_value=0.25,
        ),
        FeatureDefinition(
            name="merchant_tenure_days",
            type=FeatureType.FLOAT.value,
            description="Days merchant has been actively processing on gateway since onboarding approval.",
            entity="merchant",
            source="postgresql.public.merchant_profiles",
            timestamp=CATALOG_TIMESTAMP,
            owner="core-data@lakeflow.io",
            version="1.0.0",
            tags=["tenure", "trust"],
            freshness_sla_seconds=86400,
            default_value=450.0,
        ),
        FeatureDefinition(
            name="merchant_is_high_risk_mcc",
            type=FeatureType.BOOL.value,
            description="Boolean flag indicating whether merchant belongs to high-risk category (crypto, adult, gambling).",
            entity="merchant",
            source="postgresql.public.merchant_profiles",
            timestamp=CATALOG_TIMESTAMP,
            owner="compliance@lakeflow.io",
            version="1.0.0",
            tags=["mcc", "high-risk"],
            freshness_sla_seconds=86400,
            default_value=False,
        ),
        FeatureDefinition(
            name="merchant_is_card_not_present_only",
            type=FeatureType.BOOL.value,
            description="True if merchant strictly processes CNP online transactions with no physical POS terminals.",
            entity="merchant",
            source="postgresql.public.merchant_profiles",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.0.0",
            tags=["channel", "cnp"],
            freshness_sla_seconds=86400,
            default_value=True,
        ),
        FeatureDefinition(
            name="merchant_international_tx_ratio_30d",
            type=FeatureType.FLOAT.value,
            description="Ratio of transactions processed with foreign-issued payment cards.",
            entity="merchant",
            source="postgresql.analytics.merchant_monthly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["international", "cross-border"],
            freshness_sla_seconds=14400,
            default_value=0.08,
        ),
        FeatureDefinition(
            name="merchant_midnight_tx_ratio_7d",
            type=FeatureType.FLOAT.value,
            description="Proportion of transactions processed between 00:00 and 05:00 local merchant time.",
            entity="merchant",
            source="postgresql.analytics.merchant_weekly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["temporal", "night-activity"],
            freshness_sla_seconds=7200,
            default_value=0.04,
        ),
        FeatureDefinition(
            name="merchant_terminal_count",
            type=FeatureType.INT.value,
            description="Number of authorized hardware/virtual POS terminals registered to merchant ID.",
            entity="merchant",
            source="postgresql.terminals.hardware_inventory",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-ops@lakeflow.io",
            version="1.0.0",
            tags=["terminal", "hardware"],
            freshness_sla_seconds=86400,
            default_value=4,
        ),
        FeatureDefinition(
            name="merchant_manual_entry_ratio_30d",
            type=FeatureType.FLOAT.value,
            description="Proportion of transactions manually keyed in without chip or swipe.",
            entity="merchant",
            source="postgresql.analytics.merchant_monthly_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["keyed-entry", "card-testing"],
            freshness_sla_seconds=14400,
            default_value=0.015,
        ),
        FeatureDefinition(
            name="merchant_daily_volume_limit",
            type=FeatureType.FLOAT.value,
            description="Maximum daily settlement capacity approved by merchant underwriting in USD.",
            entity="merchant",
            source="postgresql.compliance.merchant_limits",
            timestamp=CATALOG_TIMESTAMP,
            owner="credit-risk@lakeflow.io",
            version="1.0.0",
            tags=["capacity", "limits"],
            freshness_sla_seconds=86400,
            default_value=50000.0,
        ),
        FeatureDefinition(
            name="merchant_daily_volume_utilization",
            type=FeatureType.FLOAT.value,
            description="Current 24h processed volume divided by daily approved cap.",
            entity="merchant",
            source="postgresql.analytics.merchant_daily_metrics",
            timestamp=CATALOG_TIMESTAMP,
            owner="merchant-risk@lakeflow.io",
            version="1.1.0",
            tags=["limit-utilization"],
            freshness_sla_seconds=900,
            default_value=0.37,
        ),
        FeatureDefinition(
            name="merchant_suspicious_velocity_flag",
            type=FeatureType.BOOL.value,
            description="Automated signal triggered if hourly volume exceeds 500% of rolling 30-day hourly baseline.",
            entity="merchant",
            source="postgresql.analytics.anomaly_detector",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.2.0",
            tags=["anomaly", "burst-detection", "alert"],
            freshness_sla_seconds=300,
            default_value=False,
        ),
        FeatureDefinition(
            name="merchant_kyc_status",
            type=FeatureType.INT.value,
            description="Merchant onboarding verification tier (1: Unverified, 2: Documented, 3: Full Beneficial Owner Audit).",
            entity="merchant",
            source="postgresql.compliance.kyb_audits",
            timestamp=CATALOG_TIMESTAMP,
            owner="compliance@lakeflow.io",
            version="1.0.0",
            tags=["kyb", "compliance"],
            freshness_sla_seconds=86400,
            default_value=3,
        ),
    ]
    features.extend(merchant_features)

    # =========================================================================
    # 3. TRANSACTION ENTITY FEATURES (35 Features)
    # =========================================================================
    tx_features = [
        FeatureDefinition(
            name="tx_amount",
            type=FeatureType.FLOAT.value,
            description="Nominal requested transaction amount in base currency (USD).",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="core-payment@lakeflow.io",
            version="1.0.0",
            tags=["amount", "core-signal"],
            freshness_sla_seconds=60,
            default_value=50.0,
        ),
        FeatureDefinition(
            name="tx_amount_to_customer_avg_ratio",
            type=FeatureType.FLOAT.value,
            description="Transaction amount divided by customer 30-day average spend.",
            entity="transaction",
            source="postgresql.analytics.tx_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.2.0",
            tags=["ratio", "spend-anomaly"],
            freshness_sla_seconds=60,
            default_value=1.0,
        ),
        FeatureDefinition(
            name="tx_amount_to_customer_max_ratio",
            type=FeatureType.FLOAT.value,
            description="Transaction amount divided by customer historical 30-day max spend.",
            entity="transaction",
            source="postgresql.analytics.tx_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.2.0",
            tags=["ratio", "spike"],
            freshness_sla_seconds=60,
            default_value=0.25,
        ),
        FeatureDefinition(
            name="tx_amount_to_merchant_avg_ratio",
            type=FeatureType.FLOAT.value,
            description="Transaction amount divided by merchant 30-day mean ticket size.",
            entity="transaction",
            source="postgresql.analytics.tx_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["ratio", "merchant-fit"],
            freshness_sla_seconds=60,
            default_value=0.91,
        ),
        FeatureDefinition(
            name="tx_hour_of_day",
            type=FeatureType.INT.value,
            description="Hour of day (0-23 in UTC) when authorization was received.",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["temporal", "cyclical"],
            freshness_sla_seconds=60,
            default_value=14,
        ),
        FeatureDefinition(
            name="tx_day_of_week",
            type=FeatureType.INT.value,
            description="Day of week integer (0: Monday through 6: Sunday).",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["temporal", "day"],
            freshness_sla_seconds=60,
            default_value=3,
        ),
        FeatureDefinition(
            name="tx_is_weekend",
            type=FeatureType.BOOL.value,
            description="Boolean flag indicating whether transaction occurred on Saturday or Sunday.",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["temporal", "weekend"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_is_night",
            type=FeatureType.BOOL.value,
            description="True if transaction occurred between 23:00 and 05:00 customer local time.",
            entity="transaction",
            source="postgresql.analytics.tx_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["temporal", "night"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_seconds_since_last_customer_tx",
            type=FeatureType.FLOAT.value,
            description="Number of seconds elapsed since the customer previous transaction.",
            entity="transaction",
            source="postgresql.analytics.tx_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.3.0",
            tags=["velocity", "rapid-fire"],
            freshness_sla_seconds=60,
            default_value=3600.0,
        ),
        FeatureDefinition(
            name="tx_distance_from_home_km",
            type=FeatureType.FLOAT.value,
            description="Great-circle distance in km between transaction location and customer home billing address.",
            entity="transaction",
            source="postgresql.analytics.geo_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.2.0",
            tags=["geo", "distance"],
            freshness_sla_seconds=60,
            default_value=8.4,
        ),
        FeatureDefinition(
            name="tx_distance_from_last_tx_km",
            type=FeatureType.FLOAT.value,
            description="Great-circle distance in km from location of customer preceding transaction.",
            entity="transaction",
            source="postgresql.analytics.geo_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.2.0",
            tags=["geo", "trajectory"],
            freshness_sla_seconds=60,
            default_value=2.1,
        ),
        FeatureDefinition(
            name="tx_speed_from_last_tx_kmh",
            type=FeatureType.FLOAT.value,
            description="Implied physical travel speed in km/h based on distance and elapsed time between transactions.",
            entity="transaction",
            source="postgresql.analytics.geo_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.3.0",
            tags=["geo", "velocity", "impossible-travel"],
            freshness_sla_seconds=60,
            default_value=25.0,
        ),
        FeatureDefinition(
            name="tx_is_impossible_travel",
            type=FeatureType.BOOL.value,
            description="Flag indicating implied travel speed exceeding 800 km/h (impossible physical displacement).",
            entity="transaction",
            source="postgresql.analytics.geo_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.3.0",
            tags=["impossible-travel", "high-risk"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_is_foreign_country",
            type=FeatureType.BOOL.value,
            description="Flag indicating merchant country code differs from cardholder home billing country.",
            entity="transaction",
            source="postgresql.analytics.tx_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["geo", "cross-border"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_is_high_risk_country",
            type=FeatureType.BOOL.value,
            description="True if country appears on FATF/OFAC high-risk watchlists.",
            entity="transaction",
            source="postgresql.compliance.country_ratings",
            timestamp=CATALOG_TIMESTAMP,
            owner="compliance@lakeflow.io",
            version="1.0.0",
            tags=["sanctions", "compliance"],
            freshness_sla_seconds=86400,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_currency_conversion_required",
            type=FeatureType.BOOL.value,
            description="True if transaction settlement currency differs from account base currency.",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="core-payment@lakeflow.io",
            version="1.0.0",
            tags=["fx", "currency"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_exchange_rate_markup",
            type=FeatureType.FLOAT.value,
            description="FX conversion spread percentage applied to cross-currency authorization.",
            entity="transaction",
            source="postgresql.treasury.fx_rates",
            timestamp=CATALOG_TIMESTAMP,
            owner="core-payment@lakeflow.io",
            version="1.0.0",
            tags=["fx", "spread"],
            freshness_sla_seconds=3600,
            default_value=0.015,
        ),
        FeatureDefinition(
            name="tx_entry_mode_chip",
            type=FeatureType.BOOL.value,
            description="POS entry mode was EMV contact chip insertion (POS 05).",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["pos", "emv", "secure"],
            freshness_sla_seconds=60,
            default_value=True,
        ),
        FeatureDefinition(
            name="tx_entry_mode_contactless",
            type=FeatureType.BOOL.value,
            description="POS entry mode was contactless NFC tap or mobile wallet (POS 07).",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["pos", "nfc"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_entry_mode_online",
            type=FeatureType.BOOL.value,
            description="POS entry mode was Card Not Present (CNP / E-Commerce POS 01/81).",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["cnp", "online"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_entry_mode_fallback_swipe",
            type=FeatureType.BOOL.value,
            description="Magnetic stripe fallback after failed EMV chip read (severe counterfeit risk).",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["magstripe", "fallback", "counterfeit-risk"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_entry_mode_manual_keyed",
            type=FeatureType.BOOL.value,
            description="Card PAN and expiry keyed manually by merchant clerk (POS 02).",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["manual-entry", "card-testing"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_cvv_matched",
            type=FeatureType.BOOL.value,
            description="Card Security Code (CVV2/CVC2) verified successfully by issuer authorization.",
            entity="transaction",
            source="postgresql.authorizations.iso8583_responses",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["cvv", "auth-check"],
            freshness_sla_seconds=60,
            default_value=True,
        ),
        FeatureDefinition(
            name="tx_avs_street_matched",
            type=FeatureType.BOOL.value,
            description="Address Verification System (AVS) street number matched cardholder record.",
            entity="transaction",
            source="postgresql.authorizations.iso8583_responses",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["avs", "address"],
            freshness_sla_seconds=60,
            default_value=True,
        ),
        FeatureDefinition(
            name="tx_avs_zip_matched",
            type=FeatureType.BOOL.value,
            description="Address Verification System (AVS) postal / zip code matched cardholder record.",
            entity="transaction",
            source="postgresql.authorizations.iso8583_responses",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["avs", "zip"],
            freshness_sla_seconds=60,
            default_value=True,
        ),
        FeatureDefinition(
            name="tx_3ds_authenticated",
            type=FeatureType.BOOL.value,
            description="Transaction authenticated through EMV 3-D Secure protocol.",
            entity="transaction",
            source="postgresql.authorizations.threeds_logs",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.2.0",
            tags=["3ds", "sca"],
            freshness_sla_seconds=60,
            default_value=True,
        ),
        FeatureDefinition(
            name="tx_3ds_frictionless",
            type=FeatureType.BOOL.value,
            description="3DS challenge bypassed via frictionless flow based on low risk score.",
            entity="transaction",
            source="postgresql.authorizations.threeds_logs",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["3ds", "frictionless"],
            freshness_sla_seconds=60,
            default_value=True,
        ),
        FeatureDefinition(
            name="tx_is_split_bill",
            type=FeatureType.BOOL.value,
            description="Identifies sequential micro-transactions structured right under approval thresholds.",
            entity="transaction",
            source="postgresql.analytics.tx_enrichment",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["structuring", "anomaly"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_round_amount_flag",
            type=FeatureType.BOOL.value,
            description="True if amount has zero cents (e.g. $100.00, $500.00 - common in money transfer fraud).",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["round-number", "fraud-pattern"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_just_below_auth_threshold",
            type=FeatureType.BOOL.value,
            description="True if amount is structured between $980-$999 (avoiding $1,000 reporting threshold).",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="compliance@lakeflow.io",
            version="1.1.0",
            tags=["structuring", "bsa-aml"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_auth_latency_ms",
            type=FeatureType.INT.value,
            description="Issuer bank authorization response latency in milliseconds.",
            entity="transaction",
            source="postgresql.telemetry.payment_latency",
            timestamp=CATALOG_TIMESTAMP,
            owner="infra-eng@lakeflow.io",
            version="1.0.0",
            tags=["latency", "telemetry"],
            freshness_sla_seconds=60,
            default_value=120,
        ),
        FeatureDefinition(
            name="tx_retry_attempt_count",
            type=FeatureType.INT.value,
            description="Sequence count of automatic/manual payment retries with same card credentials.",
            entity="transaction",
            source="postgresql.authorizations.retry_queue",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["retry", "card-testing"],
            freshness_sla_seconds=60,
            default_value=0,
        ),
        FeatureDefinition(
            name="tx_channel_mobile_app",
            type=FeatureType.BOOL.value,
            description="True if transaction originated via native iOS or Android mobile banking client.",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["channel", "mobile"],
            freshness_sla_seconds=60,
            default_value=True,
        ),
        FeatureDefinition(
            name="tx_channel_web_browser",
            type=FeatureType.BOOL.value,
            description="True if transaction originated via desktop or mobile web browser.",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["channel", "web"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
        FeatureDefinition(
            name="tx_channel_api",
            type=FeatureType.BOOL.value,
            description="True if transaction originated through B2B direct server-to-server gateway API.",
            entity="transaction",
            source="postgresql.public.transactions",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["channel", "api"],
            freshness_sla_seconds=60,
            default_value=False,
        ),
    ]
    features.extend(tx_features)

    # =========================================================================
    # 4. DEVICE & NETWORK ENTITY FEATURES (25 Features)
    # =========================================================================
    device_features = [
        FeatureDefinition(
            name="device_tx_count_1h",
            type=FeatureType.INT.value,
            description="Count of transactions executed from this device fingerprint in trailing 1 hour.",
            entity="device",
            source="postgresql.telemetry.device_session_aggregates",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.2.0",
            tags=["velocity", "device-burst"],
            freshness_sla_seconds=300,
            default_value=1,
        ),
        FeatureDefinition(
            name="device_tx_count_24h",
            type=FeatureType.INT.value,
            description="Count of transactions executed from this device fingerprint in trailing 24 hours.",
            entity="device",
            source="postgresql.telemetry.device_session_aggregates",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.2.0",
            tags=["velocity", "daily"],
            freshness_sla_seconds=1800,
            default_value=3,
        ),
        FeatureDefinition(
            name="device_distinct_cards_24h",
            type=FeatureType.INT.value,
            description="Number of distinct card PANs used from this single device in 24 hours (card stuffing sign).",
            entity="device",
            source="postgresql.telemetry.device_session_aggregates",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.3.0",
            tags=["card-stuffing", "high-risk"],
            freshness_sla_seconds=900,
            default_value=1,
        ),
        FeatureDefinition(
            name="device_distinct_customers_7d",
            type=FeatureType.INT.value,
            description="Number of distinct customer login IDs accessed from this device in 7 days.",
            entity="device",
            source="postgresql.telemetry.device_session_aggregates",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.1.0",
            tags=["ato", "credential-sharing"],
            freshness_sla_seconds=7200,
            default_value=1,
        ),
        FeatureDefinition(
            name="device_is_emulator",
            type=FeatureType.BOOL.value,
            description="Detected emulator environment (e.g. BlueStacks, Nox, Android Studio QEMU).",
            entity="device",
            source="postgresql.telemetry.device_security_signals",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="2.0.0",
            tags=["emulator", "bot-farm", "critical"],
            freshness_sla_seconds=300,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_is_rooted_jailbroken",
            type=FeatureType.BOOL.value,
            description="Root access (su binary, Magisk) on Android or jailbreak markers on iOS.",
            entity="device",
            source="postgresql.telemetry.device_security_signals",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="2.0.0",
            tags=["rooted", "integrity"],
            freshness_sla_seconds=300,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_is_proxy_or_vpn",
            type=FeatureType.BOOL.value,
            description="Client IP belongs to commercial VPN provider (NordVPN, ExpressVPN) or residential proxy network.",
            entity="device",
            source="postgresql.telemetry.ip_intelligence",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.4.0",
            tags=["vpn", "proxy", "anonymizer"],
            freshness_sla_seconds=600,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_is_tor_exit_node",
            type=FeatureType.BOOL.value,
            description="Client connection matched active Tor exit relay list.",
            entity="device",
            source="postgresql.telemetry.ip_intelligence",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["tor", "critical"],
            freshness_sla_seconds=300,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_is_datacenter_ip",
            type=FeatureType.BOOL.value,
            description="Client connection routed from AWS, GCP, Azure, or DigitalOcean hosting ASNs.",
            entity="device",
            source="postgresql.telemetry.ip_intelligence",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.2.0",
            tags=["datacenter", "bot"],
            freshness_sla_seconds=1800,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_ip_reputation_score",
            type=FeatureType.FLOAT.value,
            description="Global threat intelligence score (0: Clean residential, 100: Known bot/malware botnet).",
            entity="device",
            source="postgresql.telemetry.ip_intelligence",
            timestamp=CATALOG_TIMESTAMP,
            owner="security@lakeflow.io",
            version="1.2.0",
            tags=["reputation", "threat-intel"],
            freshness_sla_seconds=1800,
            default_value=8.0,
        ),
        FeatureDefinition(
            name="device_ip_country_mismatch",
            type=FeatureType.BOOL.value,
            description="GeoIP country differs from customer registered home country.",
            entity="device",
            source="postgresql.telemetry.ip_intelligence",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["geoip", "mismatch"],
            freshness_sla_seconds=600,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_ip_city_distance_km",
            type=FeatureType.FLOAT.value,
            description="Distance in km between MaxMind IP location and declared shipping/billing city.",
            entity="device",
            source="postgresql.telemetry.ip_intelligence",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.0.0",
            tags=["geoip", "distance"],
            freshness_sla_seconds=600,
            default_value=12.0,
        ),
        FeatureDefinition(
            name="device_os_version_outdated",
            type=FeatureType.BOOL.value,
            description="Client operating system version is more than 3 major cycles behind active support.",
            entity="device",
            source="postgresql.telemetry.device_fingerprints",
            timestamp=CATALOG_TIMESTAMP,
            owner="security@lakeflow.io",
            version="1.0.0",
            tags=["os", "vulnerability"],
            freshness_sla_seconds=86400,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_browser_headless_flag",
            type=FeatureType.BOOL.value,
            description="Signals indicating automated Headless Chrome, Puppeteer, Selenium, or Playwright browser.",
            entity="device",
            source="postgresql.telemetry.device_fingerprints",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="2.0.0",
            tags=["bot", "headless", "automation"],
            freshness_sla_seconds=300,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_canvas_fingerprint_hash",
            type=FeatureType.STRING.value,
            description="Cryptographic MD5 hash of 2D/3D WebGL HTML5 canvas rendering idiosyncrasies.",
            entity="device",
            source="postgresql.telemetry.device_fingerprints",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.0.0",
            tags=["fingerprint", "webgl"],
            freshness_sla_seconds=86400,
            default_value="a3f789bc10d8e244",
        ),
        FeatureDefinition(
            name="device_timezone_offset_mismatch",
            type=FeatureType.BOOL.value,
            description="Discrepancy detected between browser system clock timezone and GeoIP location timezone.",
            entity="device",
            source="postgresql.telemetry.device_security_signals",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="1.1.0",
            tags=["timezone", "spoofing"],
            freshness_sla_seconds=600,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_battery_level",
            type=FeatureType.FLOAT.value,
            description="Reported client battery charge level from Web Battery API (0.00 to 1.00).",
            entity="device",
            source="postgresql.telemetry.device_telemetry_raw",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.0.0",
            tags=["hardware", "telemetry"],
            freshness_sla_seconds=300,
            default_value=0.82,
        ),
        FeatureDefinition(
            name="device_battery_charging",
            type=FeatureType.BOOL.value,
            description="Whether client reports device currently connected to external power source.",
            entity="device",
            source="postgresql.telemetry.device_telemetry_raw",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.0.0",
            tags=["hardware", "telemetry"],
            freshness_sla_seconds=300,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_screen_resolution_anomalous",
            type=FeatureType.BOOL.value,
            description="Viewport resolution matches known virtual machine default profiles (800x600, 1024x768).",
            entity="device",
            source="postgresql.telemetry.device_telemetry_raw",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.0.0",
            tags=["screen", "vm-detector"],
            freshness_sla_seconds=86400,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_touch_event_missing",
            type=FeatureType.BOOL.value,
            description="User-agent reports mobile device but ontouchstart / maxTouchPoints API is absent.",
            entity="device",
            source="postgresql.telemetry.device_security_signals",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.1.0",
            tags=["user-agent", "spoofing"],
            freshness_sla_seconds=600,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_connection_type_cellular",
            type=FeatureType.BOOL.value,
            description="Network API indicates connection via 4G/LTE/5G cellular radio carrier.",
            entity="device",
            source="postgresql.telemetry.device_telemetry_raw",
            timestamp=CATALOG_TIMESTAMP,
            owner="infra-eng@lakeflow.io",
            version="1.0.0",
            tags=["network", "carrier"],
            freshness_sla_seconds=600,
            default_value=True,
        ),
        FeatureDefinition(
            name="device_connection_type_wifi",
            type=FeatureType.BOOL.value,
            description="Network API indicates connection over local 802.11 WiFi network.",
            entity="device",
            source="postgresql.telemetry.device_telemetry_raw",
            timestamp=CATALOG_TIMESTAMP,
            owner="infra-eng@lakeflow.io",
            version="1.0.0",
            tags=["network", "wifi"],
            freshness_sla_seconds=600,
            default_value=False,
        ),
        FeatureDefinition(
            name="device_tcp_rtt_ms",
            type=FeatureType.INT.value,
            description="Estimated round trip transport layer latency in milliseconds.",
            entity="device",
            source="postgresql.telemetry.network_telemetry",
            timestamp=CATALOG_TIMESTAMP,
            owner="infra-eng@lakeflow.io",
            version="1.0.0",
            tags=["network", "rtt"],
            freshness_sla_seconds=300,
            default_value=42,
        ),
        FeatureDefinition(
            name="device_age_days",
            type=FeatureType.FLOAT.value,
            description="Days elapsed since this device fingerprint was first observed on our network.",
            entity="device",
            source="postgresql.telemetry.device_fingerprints",
            timestamp=CATALOG_TIMESTAMP,
            owner="device-risk@lakeflow.io",
            version="1.1.0",
            tags=["tenure", "trust"],
            freshness_sla_seconds=86400,
            default_value=180.0,
        ),
        FeatureDefinition(
            name="device_trust_score",
            type=FeatureType.FLOAT.value,
            description="Holistic machine learning device reputation score (0.00: Malicious bot, 1.00: Highly trusted).",
            entity="device",
            source="postgresql.analytics.device_trust_engine",
            timestamp=CATALOG_TIMESTAMP,
            owner="fraud-ml-team@lakeflow.io",
            version="2.1.0",
            tags=["trust-score", "key-metric"],
            freshness_sla_seconds=900,
            default_value=0.92,
        ),
    ]
    features.extend(device_features)

    return features
